on:
  push:
    branches: [ master ]
  pull_request:
name: build
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
  build-test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...  -coverprofile=coverage.txt -covermode=count
      - name: Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
