name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '^1.25'

      - uses: golangci/golangci-lint-action@v8

  build-test:
    strategy:
      matrix:
        go-version: [1.23.4]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...  -coverprofile=coverage.txt -covermode=count

      - name: Coverage Report
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.txt
          verbose: true
